
package proyectofinalp2_davidcastro;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    
    private String [] fuentes;
    private ArrayList<Usuario> usuarios = new ArrayList<Usuario>();
    private DefaultListModel modeloLista = new DefaultListModel();
    
    public PantallaPrincipal() {
        
        usuarios.add(new Administrador("admin", "1234"));
        fuentes = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
        
        initComponents();
        
        listFuente.setModel(modeloLista);
        agregarElementos();
        setLocationRelativeTo(null);
        //System.out.println(usuarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framePantallaInicioOS = new javax.swing.JFrame();
        panelInicioOS = new javax.swing.JPanel();
        lblIconoEditorTextoOS = new javax.swing.JLabel();
        lblEditorTextoOS = new javax.swing.JLabel();
        lblIconoExploradorArchivosOS = new javax.swing.JLabel();
        lblExploradorArchivoOS = new javax.swing.JLabel();
        lblTituloOS = new javax.swing.JLabel();
        mBarPrincipal = new javax.swing.JMenuBar();
        menuOpcionesUsuario = new javax.swing.JMenu();
        mItemCrearUsuario = new javax.swing.JMenuItem();
        mItemEditarUsuario = new javax.swing.JMenuItem();
        mItemEliminarUsuario = new javax.swing.JMenuItem();
        menuPersonalizar = new javax.swing.JMenu();
        mItemNavbarColor = new javax.swing.JMenuItem();
        mItemColorLetraNavbar = new javax.swing.JMenuItem();
        mItemFondoColor = new javax.swing.JMenuItem();
        mItemFuente = new javax.swing.JMenuItem();
        mItemFondoImagen = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();
        menuApagar = new javax.swing.JMenu();
        dialCrearUsuario = new javax.swing.JDialog();
        lblCrearUsuario = new javax.swing.JLabel();
        lblContrasenaCU = new javax.swing.JLabel();
        lblNombreCU = new javax.swing.JLabel();
        txtContrasenaCU = new javax.swing.JTextField();
        txtNombreCU = new javax.swing.JTextField();
        lblTipoCU = new javax.swing.JLabel();
        comboTipoCU = new javax.swing.JComboBox<>();
        btnCancelarCU = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JButton();
        lblIconoCrearUsuario = new javax.swing.JLabel();
        dialEditorTexto = new javax.swing.JDialog();
        panelEditorTexto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEditorTexto = new javax.swing.JTextArea();
        btnAtrasEditorTexto = new javax.swing.JButton();
        comboTamano = new javax.swing.JComboBox<>();
        comboFuentes = new javax.swing.JComboBox<>();
        comboEstilos = new javax.swing.JComboBox<>();
        lblTamano = new javax.swing.JLabel();
        lblFuente = new javax.swing.JLabel();
        lblEstilo = new javax.swing.JLabel();
        dialPersonalizarFuente = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        listFuente = new javax.swing.JList<>();
        lblPersonalizacionFuente = new javax.swing.JLabel();
        comboTamanoFuente = new javax.swing.JComboBox<>();
        comboEstiloFuente = new javax.swing.JComboBox<>();
        lblTamanoFuente = new javax.swing.JLabel();
        lblEstiloFuente = new javax.swing.JLabel();
        lblFuenteFuente = new javax.swing.JLabel();
        btnVolverFuente = new javax.swing.JButton();
        btnColorFuente = new javax.swing.JButton();
        tgBtnTitulo = new javax.swing.JToggleButton();
        lblOnOff = new javax.swing.JLabel();
        lblFondoFuente = new javax.swing.JLabel();
        panelInicioSesion = new javax.swing.JPanel();
        lblInicioSesion = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        framePantallaInicioOS.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                framePantallaInicioOSWindowClosed(evt);
            }
        });

        panelInicioOS.setBackground(new java.awt.Color(153, 153, 153));
        panelInicioOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoEditorTextoOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editor de texto.png"))); // NOI18N
        lblIconoEditorTextoOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconoEditorTextoOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconoEditorTextoOSMouseClicked(evt);
            }
        });
        panelInicioOS.add(lblIconoEditorTextoOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 140, 140));

        lblEditorTextoOS.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblEditorTextoOS.setForeground(new java.awt.Color(0, 0, 0));
        lblEditorTextoOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditorTextoOS.setText("Editor de Texto");
        panelInicioOS.add(lblEditorTextoOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 230, 70));

        lblIconoExploradorArchivosOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/explorador archivos.png"))); // NOI18N
        lblIconoExploradorArchivosOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelInicioOS.add(lblIconoExploradorArchivosOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 140, 140));

        lblExploradorArchivoOS.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblExploradorArchivoOS.setForeground(new java.awt.Color(0, 0, 0));
        lblExploradorArchivoOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExploradorArchivoOS.setText("Explorador de Archivos");
        panelInicioOS.add(lblExploradorArchivoOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 300, 70));

        lblTituloOS.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTituloOS.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloOS.setText("Pantalla de Inicio");
        panelInicioOS.add(lblTituloOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 790, 100));

        mBarPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 241, 241), 1, true));
        mBarPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mBarPrincipal.setOpaque(true);

        menuOpcionesUsuario.setForeground(new java.awt.Color(0, 0, 0));
        menuOpcionesUsuario.setText("Opciones de Usuario");
        menuOpcionesUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuOpcionesUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuOpcionesUsuario.setOpaque(true);
        menuOpcionesUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuOpcionesUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuOpcionesUsuarioMouseExited(evt);
            }
        });

        mItemCrearUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemCrearUsuario.setForeground(new java.awt.Color(0, 0, 0));
        mItemCrearUsuario.setText("Crear Usuario");
        mItemCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemCrearUsuario.setOpaque(true);
        mItemCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCrearUsuarioActionPerformed(evt);
            }
        });
        menuOpcionesUsuario.add(mItemCrearUsuario);

        mItemEditarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemEditarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        mItemEditarUsuario.setText("Editar Usuario");
        mItemEditarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemEditarUsuario.setOpaque(true);
        menuOpcionesUsuario.add(mItemEditarUsuario);

        mItemEliminarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemEliminarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        mItemEliminarUsuario.setText("Eliminar Usuario");
        mItemEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemEliminarUsuario.setOpaque(true);
        menuOpcionesUsuario.add(mItemEliminarUsuario);

        mBarPrincipal.add(menuOpcionesUsuario);

        menuPersonalizar.setForeground(new java.awt.Color(0, 0, 0));
        menuPersonalizar.setText("Personalizar");
        menuPersonalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPersonalizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuPersonalizar.setOpaque(true);
        menuPersonalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPersonalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPersonalizarMouseExited(evt);
            }
        });

        mItemNavbarColor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemNavbarColor.setForeground(new java.awt.Color(0, 0, 0));
        mItemNavbarColor.setText("Color de la barra de navegacion");
        mItemNavbarColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemNavbarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemNavbarColorActionPerformed(evt);
            }
        });
        menuPersonalizar.add(mItemNavbarColor);

        mItemColorLetraNavbar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemColorLetraNavbar.setForeground(new java.awt.Color(0, 0, 0));
        mItemColorLetraNavbar.setText("Color de letra de la barra de navegacion");
        mItemColorLetraNavbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemColorLetraNavbarActionPerformed(evt);
            }
        });
        menuPersonalizar.add(mItemColorLetraNavbar);

        mItemFondoColor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemFondoColor.setForeground(new java.awt.Color(0, 0, 0));
        mItemFondoColor.setText("Color del fondo de pantalla");
        mItemFondoColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemFondoColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemFondoColorActionPerformed(evt);
            }
        });
        menuPersonalizar.add(mItemFondoColor);

        mItemFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemFuente.setForeground(new java.awt.Color(0, 0, 0));
        mItemFuente.setText("Fuente del fondo de pantalla");
        mItemFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemFuenteActionPerformed(evt);
            }
        });
        menuPersonalizar.add(mItemFuente);

        mItemFondoImagen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemFondoImagen.setForeground(new java.awt.Color(0, 0, 0));
        mItemFondoImagen.setText("Fondo de pantalla");
        mItemFondoImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemFondoImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemFondoImagenActionPerformed(evt);
            }
        });
        menuPersonalizar.add(mItemFondoImagen);

        mBarPrincipal.add(menuPersonalizar);

        menuLogout.setForeground(new java.awt.Color(0, 0, 0));
        menuLogout.setText("Logout");
        menuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuLogout.setOpaque(true);
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLogoutMouseExited(evt);
            }
        });
        mBarPrincipal.add(menuLogout);

        menuApagar.setForeground(new java.awt.Color(0, 0, 0));
        menuApagar.setText("Apagar");
        menuApagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuApagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuApagar.setOpaque(true);
        menuApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuApagarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuApagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuApagarMouseExited(evt);
            }
        });
        mBarPrincipal.add(menuApagar);

        framePantallaInicioOS.setJMenuBar(mBarPrincipal);

        javax.swing.GroupLayout framePantallaInicioOSLayout = new javax.swing.GroupLayout(framePantallaInicioOS.getContentPane());
        framePantallaInicioOS.getContentPane().setLayout(framePantallaInicioOSLayout);
        framePantallaInicioOSLayout.setHorizontalGroup(
            framePantallaInicioOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(framePantallaInicioOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelInicioOS, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE))
        );
        framePantallaInicioOSLayout.setVerticalGroup(
            framePantallaInicioOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(framePantallaInicioOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelInicioOS, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
        );

        dialCrearUsuario.setBackground(new java.awt.Color(102, 102, 102));
        dialCrearUsuario.setModal(true);
        dialCrearUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCrearUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblCrearUsuario.setText("Crear Usuario");
        dialCrearUsuario.getContentPane().add(lblCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 163, 50));

        lblContrasenaCU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblContrasenaCU.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasenaCU.setText("Contraseña:");
        dialCrearUsuario.getContentPane().add(lblContrasenaCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 25));

        lblNombreCU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreCU.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCU.setText("Nombre:");
        dialCrearUsuario.getContentPane().add(lblNombreCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 25));

        txtContrasenaCU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtContrasenaCU.setForeground(new java.awt.Color(0, 0, 0));
        txtContrasenaCU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dialCrearUsuario.getContentPane().add(txtContrasenaCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 250, 30));

        txtNombreCU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombreCU.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreCU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dialCrearUsuario.getContentPane().add(txtNombreCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 250, 30));

        lblTipoCU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoCU.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoCU.setText("Tipo:");
        dialCrearUsuario.getContentPane().add(lblTipoCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 50, 25));

        comboTipoCU.setBackground(new java.awt.Color(255, 255, 255));
        comboTipoCU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboTipoCU.setForeground(new java.awt.Color(0, 0, 0));
        comboTipoCU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Invitado" }));
        comboTipoCU.setSelectedIndex(-1);
        comboTipoCU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        comboTipoCU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboTipoCU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboTipoCUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comboTipoCUMouseExited(evt);
            }
        });
        dialCrearUsuario.getContentPane().add(comboTipoCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 160, 30));

        btnCancelarCU.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelarCU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelarCU.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarCU.setText("Cancelar");
        btnCancelarCU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelarCU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarCUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarCUMouseExited(evt);
            }
        });
        btnCancelarCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCUActionPerformed(evt);
            }
        });
        dialCrearUsuario.getContentPane().add(btnCancelarCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 60, 30));

        btnCrearUsuario.setBackground(new java.awt.Color(0, 0, 0));
        btnCrearUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearUsuario.setText("Crear Usuario");
        btnCrearUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseExited(evt);
            }
        });
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });
        dialCrearUsuario.getContentPane().add(btnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 140, 40));

        lblIconoCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo login.jpg"))); // NOI18N
        dialCrearUsuario.getContentPane().add(lblIconoCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 470));

        dialEditorTexto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaEditorTexto.setColumns(20);
        txtAreaEditorTexto.setRows(5);
        jScrollPane1.setViewportView(txtAreaEditorTexto);

        btnAtrasEditorTexto.setBackground(new java.awt.Color(153, 0, 0));
        btnAtrasEditorTexto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtrasEditorTexto.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasEditorTexto.setText("Atras");
        btnAtrasEditorTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasEditorTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtrasEditorTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtrasEditorTextoMouseExited(evt);
            }
        });

        comboTamano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        comboTamano.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTamanoItemStateChanged(evt);
            }
        });

        comboFuentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        comboFuentes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFuentesItemStateChanged(evt);
            }
        });

        comboEstilos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Normal", "Negrita", "Cursiva" }));
        comboEstilos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEstilosItemStateChanged(evt);
            }
        });

        lblTamano.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTamano.setForeground(new java.awt.Color(0, 0, 0));
        lblTamano.setText("Tamaño de letra");

        lblFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFuente.setForeground(new java.awt.Color(0, 0, 0));
        lblFuente.setText("Fuentes");

        lblEstilo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstilo.setForeground(new java.awt.Color(0, 0, 0));
        lblEstilo.setText("Estilo de letra");

        javax.swing.GroupLayout panelEditorTextoLayout = new javax.swing.GroupLayout(panelEditorTexto);
        panelEditorTexto.setLayout(panelEditorTextoLayout);
        panelEditorTextoLayout.setHorizontalGroup(
            panelEditorTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditorTextoLayout.createSequentialGroup()
                .addGroup(panelEditorTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditorTextoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAtrasEditorTexto))
                    .addGroup(panelEditorTextoLayout.createSequentialGroup()
                        .addGroup(panelEditorTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelEditorTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboFuentes, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFuente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelEditorTextoLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(panelEditorTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboEstilos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        panelEditorTextoLayout.setVerticalGroup(
            panelEditorTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditorTextoLayout.createSequentialGroup()
                .addGroup(panelEditorTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelEditorTextoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(panelEditorTextoLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(panelEditorTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTamano)
                            .addComponent(lblFuente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEditorTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboFuentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstilo)
                        .addGap(4, 4, 4)
                        .addComponent(comboEstilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                        .addComponent(btnAtrasEditorTexto)))
                .addContainerGap())
        );

        dialEditorTexto.getContentPane().add(panelEditorTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 890, 610));

        dialPersonalizarFuente.setModal(true);
        dialPersonalizarFuente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listFuente.setBackground(new java.awt.Color(75, 75, 75));
        listFuente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listFuente.setForeground(new java.awt.Color(255, 255, 255));
        listFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listFuente.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listFuenteValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listFuente);

        dialPersonalizarFuente.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, 110));

        lblPersonalizacionFuente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPersonalizacionFuente.setForeground(new java.awt.Color(255, 255, 255));
        lblPersonalizacionFuente.setText("Personalizacion de Fuente");
        dialPersonalizarFuente.getContentPane().add(lblPersonalizacionFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 230, 35));

        comboTamanoFuente.setBackground(new java.awt.Color(75, 75, 75));
        comboTamanoFuente.setForeground(new java.awt.Color(255, 255, 255));
        comboTamanoFuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        comboTamanoFuente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 75, 75)));
        comboTamanoFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboTamanoFuente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTamanoFuenteItemStateChanged(evt);
            }
        });
        dialPersonalizarFuente.getContentPane().add(comboTamanoFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, -1));

        comboEstiloFuente.setBackground(new java.awt.Color(75, 75, 75));
        comboEstiloFuente.setForeground(new java.awt.Color(255, 255, 255));
        comboEstiloFuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Normal", "Negrita", "Cursiva" }));
        comboEstiloFuente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 75, 75)));
        comboEstiloFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboEstiloFuente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEstiloFuenteItemStateChanged(evt);
            }
        });
        dialPersonalizarFuente.getContentPane().add(comboEstiloFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, -1));

        lblTamanoFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTamanoFuente.setForeground(new java.awt.Color(255, 255, 255));
        lblTamanoFuente.setText("Tamano de letra");
        dialPersonalizarFuente.getContentPane().add(lblTamanoFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, -1));

        lblEstiloFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstiloFuente.setForeground(new java.awt.Color(255, 255, 255));
        lblEstiloFuente.setText("Estilo de letra");
        dialPersonalizarFuente.getContentPane().add(lblEstiloFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        lblFuenteFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFuenteFuente.setForeground(new java.awt.Color(255, 255, 255));
        lblFuenteFuente.setText("Fuente");
        dialPersonalizarFuente.getContentPane().add(lblFuenteFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 100, -1));

        btnVolverFuente.setBackground(new java.awt.Color(153, 0, 0));
        btnVolverFuente.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnVolverFuente.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverFuente.setText("Volver");
        btnVolverFuente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolverFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverFuente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverFuenteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverFuenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverFuenteMouseExited(evt);
            }
        });
        dialPersonalizarFuente.getContentPane().add(btnVolverFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, -1));

        btnColorFuente.setBackground(new java.awt.Color(75, 75, 75));
        btnColorFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnColorFuente.setForeground(new java.awt.Color(255, 255, 255));
        btnColorFuente.setText("Color de letra");
        btnColorFuente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 75, 75)));
        btnColorFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnColorFuente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColorFuenteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnColorFuenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnColorFuenteMouseExited(evt);
            }
        });
        dialPersonalizarFuente.getContentPane().add(btnColorFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 100, 30));

        tgBtnTitulo.setBackground(new java.awt.Color(75, 75, 75));
        tgBtnTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tgBtnTitulo.setForeground(new java.awt.Color(255, 255, 255));
        tgBtnTitulo.setText("Hacer cambios al Titulo");
        tgBtnTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tgBtnTitulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tgBtnTituloItemStateChanged(evt);
            }
        });
        dialPersonalizarFuente.getContentPane().add(tgBtnTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 223, -1, 30));

        lblOnOff.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOnOff.setForeground(new java.awt.Color(255, 0, 0));
        lblOnOff.setText("OFF");
        dialPersonalizarFuente.getContentPane().add(lblOnOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 60, 30));

        lblFondoFuente.setBackground(new java.awt.Color(51, 51, 51));
        lblFondoFuente.setOpaque(true);
        dialPersonalizarFuente.getContentPane().add(lblFondoFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 270));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInicioSesion.setPreferredSize(new java.awt.Dimension(507, 600));
        panelInicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblInicioSesion.setText("Inicio de sesion");
        panelInicioSesion.add(lblInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 180, -1));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono inicio sesion.jpg"))); // NOI18N
        panelInicioSesion.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        lblContrasena.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contraseña:");
        panelInicioSesion.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 30));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        panelInicioSesion.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 30));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelInicioSesion.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 250, 30));

        txtContrasena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(0, 0, 0));
        txtContrasena.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelInicioSesion.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 250, 30));

        btnIniciarSesion.setBackground(new java.awt.Color(0, 0, 0));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar sesion");
        btnIniciarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseExited(evt);
            }
        });
        panelInicioSesion.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 130, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Si es primera vez, utiliza (Nombre = admin / Contraseña = 1234) para poder entrar.");
        panelInicioSesion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 470, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo login.jpg"))); // NOI18N
        panelInicioSesion.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseClicked
        if (verificarUsuario(txtNombre.getText(), txtContrasena.getText())){
            txtNombre.setText("");
            txtContrasena.setText("");
            
            framePantallaInicioOS.pack();
            framePantallaInicioOS.setVisible(true);
            framePantallaInicioOS.setLocationRelativeTo(this);
            dispose();
            //JOptionPane.showMessageDialog(this, "Sesion iniciada");
        } else {
            JOptionPane.showMessageDialog(this, "No existe ese usuario","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIniciarSesionMouseClicked

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estas seguro que quieres cerrar sesion?", "Advertencia", JOptionPane.YES_NO_CANCEL_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            framePantallaInicioOS.dispose();
            setVisible(true);
        }
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void btnAtrasEditorTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasEditorTextoMouseClicked
        dialEditorTexto.dispose();
        framePantallaInicioOS.setVisible(true);
    }//GEN-LAST:event_btnAtrasEditorTextoMouseClicked

    private void comboTamanoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTamanoItemStateChanged
        int tamano = Integer.parseInt(comboTamano.getSelectedItem()+"");
        String nombre = txtAreaEditorTexto.getFont().getFontName();
        int estilo = txtAreaEditorTexto.getFont().getStyle();
        txtAreaEditorTexto.setFont(new Font(nombre, estilo, tamano));
    }//GEN-LAST:event_comboTamanoItemStateChanged

    private void comboFuentesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFuentesItemStateChanged
        int tamano = txtAreaEditorTexto.getFont().getSize();
        String nombre = comboFuentes.getSelectedItem()+"";
        int estilo = txtAreaEditorTexto.getFont().getStyle();
        txtAreaEditorTexto.setFont(new Font(nombre, estilo, tamano));
    }//GEN-LAST:event_comboFuentesItemStateChanged

    private void comboEstilosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEstilosItemStateChanged
        int tamano = txtAreaEditorTexto.getFont().getSize();
        String nombre = txtAreaEditorTexto.getFont().getFontName();
        int estilo = comboEstilos.getSelectedIndex();
        switch (estilo){
            case 1:
                txtAreaEditorTexto.setFont(new Font(nombre, Font.PLAIN, tamano));
                break;
            case 2:
                txtAreaEditorTexto.setFont(new Font(nombre, Font.BOLD, tamano));
                break;
            case 3:
                txtAreaEditorTexto.setFont(new Font(nombre, Font.ITALIC, tamano));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_comboEstilosItemStateChanged

    private void btnCancelarCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCUActionPerformed
        dialCrearUsuario.dispose();
    }//GEN-LAST:event_btnCancelarCUActionPerformed

    private void mItemCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCrearUsuarioActionPerformed
        dialCrearUsuario.pack();
        dialCrearUsuario.setLocationRelativeTo(this);
        dialCrearUsuario.setVisible(true);
    }//GEN-LAST:event_mItemCrearUsuarioActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        if ((txtNombreCU.getText().isBlank() && txtContrasenaCU.getText().isBlank() && comboTipoCU.getSelectedIndex() == -1) || txtNombreCU.getText().isBlank() || txtContrasenaCU.getText().isBlank() || comboTipoCU.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(rootPane, "No has ingresado los campos necesarios", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (comboTipoCU.getSelectedIndex() == 0) {
                usuarios.add(new Administrador(txtNombreCU.getText(), txtContrasenaCU.getText()));
            } else {
                usuarios.add(new Invitado(txtNombreCU.getText(), txtContrasenaCU.getText()));
            }
            JOptionPane.showMessageDialog(rootPane, "Usuario creado exitosamente");
            dialCrearUsuario.dispose();
        }
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void lblIconoEditorTextoOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconoEditorTextoOSMouseClicked
        framePantallaInicioOS.dispose();
        dialEditorTexto.pack();
        dialEditorTexto.setLocationRelativeTo(this);
        dialEditorTexto.setVisible(true);
    }//GEN-LAST:event_lblIconoEditorTextoOSMouseClicked

    private void menuApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuApagarMouseClicked
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estas seguro que quieres apagar el sistema operativo?", "Advertencia", JOptionPane.YES_NO_CANCEL_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuApagarMouseClicked
    
    Color colorSeleccionadoTemp;
    private void mItemNavbarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemNavbarColorActionPerformed
        Color colorSeleccionado = JColorChooser.showDialog(this, "Escoge el color de la barra de navegacion", Color.BLACK);
        mBarPrincipal.setBackground(colorSeleccionado);
        menuPersonalizar.setBackground(colorSeleccionado);
        menuApagar.setBackground(colorSeleccionado);
        menuLogout.setBackground(colorSeleccionado);
        menuOpcionesUsuario.setBackground(colorSeleccionado);
        colorSeleccionadoTemp = colorSeleccionado;
    }//GEN-LAST:event_mItemNavbarColorActionPerformed

    private void mItemFondoColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemFondoColorActionPerformed
        Color colorseleccionado = JColorChooser.showDialog(this, "Escoge el color del fondo", Color.BLACK);
        panelInicioOS.setBackground(colorseleccionado);
    }//GEN-LAST:event_mItemFondoColorActionPerformed

    private void btnIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseEntered
        btnIniciarSesion.setBackground(Color.decode("#444444"));
    }//GEN-LAST:event_btnIniciarSesionMouseEntered

    private void btnIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseExited
        btnIniciarSesion.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnIniciarSesionMouseExited

    private void menuOpcionesUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOpcionesUsuarioMouseEntered
        menuOpcionesUsuario.setBackground(Color.decode("#898989"));
    }//GEN-LAST:event_menuOpcionesUsuarioMouseEntered

    private void menuOpcionesUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOpcionesUsuarioMouseExited
        menuOpcionesUsuario.setBackground(colorSeleccionadoTemp);
    }//GEN-LAST:event_menuOpcionesUsuarioMouseExited

    private void menuPersonalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPersonalizarMouseEntered
        menuPersonalizar.setBackground(Color.decode("#898989"));
    }//GEN-LAST:event_menuPersonalizarMouseEntered

    private void menuPersonalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPersonalizarMouseExited
        menuPersonalizar.setBackground(colorSeleccionadoTemp);
    }//GEN-LAST:event_menuPersonalizarMouseExited

    private void menuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseEntered
        menuLogout.setBackground(Color.decode("#898989"));
    }//GEN-LAST:event_menuLogoutMouseEntered

    private void menuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseExited
        menuLogout.setBackground(colorSeleccionadoTemp);
    }//GEN-LAST:event_menuLogoutMouseExited

    private void menuApagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuApagarMouseEntered
        menuApagar.setBackground(Color.decode("#898989"));
    }//GEN-LAST:event_menuApagarMouseEntered

    private void menuApagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuApagarMouseExited
        menuApagar.setBackground(colorSeleccionadoTemp);
    }//GEN-LAST:event_menuApagarMouseExited

    private void comboTipoCUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTipoCUMouseEntered
        comboTipoCU.setBackground(Color.decode("#898989"));
    }//GEN-LAST:event_comboTipoCUMouseEntered

    private void comboTipoCUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTipoCUMouseExited
        comboTipoCU.setBackground(Color.WHITE);
    }//GEN-LAST:event_comboTipoCUMouseExited

    private void btnCrearUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseEntered
        btnCrearUsuario.setBackground(Color.decode("#444444"));
    }//GEN-LAST:event_btnCrearUsuarioMouseEntered

    private void btnCrearUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseExited
        btnCrearUsuario.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnCrearUsuarioMouseExited

    private void btnCancelarCUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarCUMouseEntered
        btnCancelarCU.setBackground(Color.decode("#5b0000"));
    }//GEN-LAST:event_btnCancelarCUMouseEntered

    private void btnCancelarCUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarCUMouseExited
        btnCancelarCU.setBackground(Color.decode("#990000"));
    }//GEN-LAST:event_btnCancelarCUMouseExited

    private void btnAtrasEditorTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasEditorTextoMouseEntered
        btnAtrasEditorTexto.setBackground(Color.decode("#5b0000"));
    }//GEN-LAST:event_btnAtrasEditorTextoMouseEntered

    private void btnAtrasEditorTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasEditorTextoMouseExited
        btnAtrasEditorTexto.setBackground(Color.decode("#990000"));
    }//GEN-LAST:event_btnAtrasEditorTextoMouseExited

    private void btnVolverFuenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverFuenteMouseClicked
        dialPersonalizarFuente.dispose();
    }//GEN-LAST:event_btnVolverFuenteMouseClicked

    private void mItemFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemFuenteActionPerformed
        dialPersonalizarFuente.pack();
        dialPersonalizarFuente.setLocationRelativeTo(this);
        dialPersonalizarFuente.setVisible(true);
    }//GEN-LAST:event_mItemFuenteActionPerformed

    private void comboTamanoFuenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTamanoFuenteItemStateChanged
        int tamano = Integer.parseInt(comboTamanoFuente.getSelectedItem()+"");
        String nombre = lblEditorTextoOS.getFont().getFontName(), nombreTitulo = lblTituloOS.getFont().getFontName();
        int estilo = lblEditorTextoOS.getFont().getStyle(), estiloTitulo = lblTituloOS.getFont().getStyle();
        
        if (tgBtnTitulo.isSelected()) {
            lblTituloOS.setFont(new Font(nombreTitulo, estiloTitulo, tamano));
        } else {
            lblEditorTextoOS.setFont(new Font(nombre, estilo, tamano));
            lblExploradorArchivoOS.setFont(new Font(nombre, estilo, tamano));
        }
    }//GEN-LAST:event_comboTamanoFuenteItemStateChanged

    private void btnColorFuenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorFuenteMouseEntered
        btnColorFuente.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnColorFuenteMouseEntered

    private void btnColorFuenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorFuenteMouseExited
        btnColorFuente.setBackground(Color.decode("#4B4B4B"));
    }//GEN-LAST:event_btnColorFuenteMouseExited

    private void btnVolverFuenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverFuenteMouseEntered
        btnVolverFuente.setBackground(Color.decode("#5b0000"));
    }//GEN-LAST:event_btnVolverFuenteMouseEntered

    private void btnVolverFuenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverFuenteMouseExited
        btnVolverFuente.setBackground(Color.decode("#990000"));
    }//GEN-LAST:event_btnVolverFuenteMouseExited

    private void btnColorFuenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorFuenteMouseClicked
        Color colorSeleccionado = JColorChooser.showDialog(this, "Escoge el color de la letra de la pantalla de inicio", Color.BLACK);
        
        if (tgBtnTitulo.isSelected()) {
            lblTituloOS.setForeground(colorSeleccionado);
        } else {
            lblEditorTextoOS.setForeground(colorSeleccionado);
            lblExploradorArchivoOS.setForeground(colorSeleccionado);
        }
    }//GEN-LAST:event_btnColorFuenteMouseClicked

    private void listFuenteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listFuenteValueChanged
        int tamano = lblEditorTextoOS.getFont().getSize(), tamanoTitulo = lblTituloOS.getFont().getSize();
        String nombre = listFuente.getSelectedValue();
        int estilo = lblEditorTextoOS.getFont().getStyle(), estiloTitulo = lblTituloOS.getFont().getStyle();
        
        if (tgBtnTitulo.isSelected()) {
            lblTituloOS.setFont(new Font(nombre, estiloTitulo, tamanoTitulo));
        } else {
            lblEditorTextoOS.setFont(new Font(nombre, estilo, tamano));
            lblExploradorArchivoOS.setFont(new Font(nombre, estilo, tamano));
        }
    }//GEN-LAST:event_listFuenteValueChanged

    private void comboEstiloFuenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEstiloFuenteItemStateChanged
        int tamano = lblEditorTextoOS.getFont().getSize(), tamanoTitulo = lblTituloOS.getFont().getSize();
        String nombre = lblEditorTextoOS.getFont().getFontName(), nombreTitulo = lblTituloOS.getFont().getFontName();
        int estilo = comboEstiloFuente.getSelectedIndex();
        
        if (tgBtnTitulo.isSelected()) {
            switch (estilo){
            case 1:
                lblTituloOS.setFont(new Font(nombreTitulo,Font.PLAIN,tamanoTitulo));
                break;
            case 2:
                lblTituloOS.setFont(new Font(nombreTitulo,Font.BOLD,tamanoTitulo));
                break;
            case 3:
                lblTituloOS.setFont(new Font(nombreTitulo,Font.ITALIC,tamanoTitulo));
                break;
            default:
                break;
            }
        } else {
            switch (estilo){
                case 1:
                    lblEditorTextoOS.setFont(new Font(nombre, Font.PLAIN, tamano));
                    lblExploradorArchivoOS.setFont(new Font(nombre, Font.PLAIN, tamano));
                    break;
                case 2:
                    lblEditorTextoOS.setFont(new Font(nombre, Font.BOLD, tamano));
                    lblExploradorArchivoOS.setFont(new Font(nombre, Font.BOLD, tamano));
                    break;
                case 3:
                    lblEditorTextoOS.setFont(new Font(nombre, Font.ITALIC, tamano));
                    lblExploradorArchivoOS.setFont(new Font(nombre, Font.ITALIC, tamano));
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_comboEstiloFuenteItemStateChanged

    private void framePantallaInicioOSWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_framePantallaInicioOSWindowClosed
        //-----------------------------------------------------------------------------------------------------\\
    }//GEN-LAST:event_framePantallaInicioOSWindowClosed

    private void mItemColorLetraNavbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemColorLetraNavbarActionPerformed
        Color colorSeleccionado = JColorChooser.showDialog(this, "Escoge el color de la letra de la barra de navegacion", Color.BLACK);
        menuOpcionesUsuario.setForeground(colorSeleccionado);
        menuPersonalizar.setForeground(colorSeleccionado);
        menuLogout.setForeground(colorSeleccionado);
        menuApagar.setForeground(colorSeleccionado);
    }//GEN-LAST:event_mItemColorLetraNavbarActionPerformed

    private void tgBtnTituloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tgBtnTituloItemStateChanged
        if (tgBtnTitulo.isSelected()) {
            lblOnOff.setText("ON");
            lblOnOff.setForeground(Color.GREEN);
        } else {
            lblOnOff.setText("OFF");
            lblOnOff.setForeground(Color.RED);
        }
    }//GEN-LAST:event_tgBtnTituloItemStateChanged

    private void mItemFondoImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemFondoImagenActionPerformed
        //-----------------------------------------------------------------------------------\\
    }//GEN-LAST:event_mItemFondoImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }
    
    private boolean verificarUsuario(String nombre, String contrasena){
        boolean isUsuario = true;
        for (Usuario usuario : usuarios) {
            if (nombre.equals(usuario.getNombre()) && contrasena.equals(usuario.getContrasena())){
                isUsuario = true;
                break;
            } else {
                isUsuario = false;
            }
        }
        return isUsuario;
    }
    
    private void agregarElementos(){
        for (int i = 10; i <= 60; i+=2) {
            comboTamano.addItem(i+"");
            comboTamanoFuente.addItem(i+"");
        }
        for (int i = 0; i < fuentes.length; i++) {
            comboFuentes.addItem(fuentes[i]);
            modeloLista.addElement(fuentes[i]);
        }
    }
    
    private Usuario usuarioActual(String nombre, String contrasena){
        Usuario usuario = new Usuario();
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getNombre().equals(nombre) && usuarios.get(i).getContrasena().equals(contrasena)){
                usuario = usuarios.get(i);
                break;
            }
        }
        return usuario;
    }
    
    /*private void barraDeProgreso() {
        frameProgressBar.pack();
        frameProgressBar.setVisible(true); 
        frameProgressBar.setLocationRelativeTo(this);
        int contador = 0;
        System.out.println(frameProgressBar.isVisible());
        Thread thread = new Thread() {
            public void run() {
                pBarCarga.setValue(0);
                while (pBarCarga.getValue() < 100) {
                    pBarCarga.setValue(pBarCarga.getValue() + 5);
                    try {
                        Thread.sleep(50);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    if (pBarCarga.getValue() == 100){
                        frameProgressBar.setVisible(false);
                        frameProgressBar.dispose();
                    }
                }
            }
        };
        thread.start();
        
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasEditorTexto;
    private javax.swing.JButton btnCancelarCU;
    private javax.swing.JButton btnColorFuente;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnVolverFuente;
    private javax.swing.JComboBox<String> comboEstiloFuente;
    private javax.swing.JComboBox<String> comboEstilos;
    private javax.swing.JComboBox<String> comboFuentes;
    private javax.swing.JComboBox<String> comboTamano;
    private javax.swing.JComboBox<String> comboTamanoFuente;
    private javax.swing.JComboBox<String> comboTipoCU;
    private javax.swing.JDialog dialCrearUsuario;
    private javax.swing.JDialog dialEditorTexto;
    private javax.swing.JDialog dialPersonalizarFuente;
    private javax.swing.JFrame framePantallaInicioOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblContrasenaCU;
    private javax.swing.JLabel lblCrearUsuario;
    private javax.swing.JLabel lblEditorTextoOS;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblEstiloFuente;
    private javax.swing.JLabel lblExploradorArchivoOS;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondoFuente;
    private javax.swing.JLabel lblFuente;
    private javax.swing.JLabel lblFuenteFuente;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIconoCrearUsuario;
    private javax.swing.JLabel lblIconoEditorTextoOS;
    private javax.swing.JLabel lblIconoExploradorArchivosOS;
    private javax.swing.JLabel lblInicioSesion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreCU;
    private javax.swing.JLabel lblOnOff;
    private javax.swing.JLabel lblPersonalizacionFuente;
    private javax.swing.JLabel lblTamano;
    private javax.swing.JLabel lblTamanoFuente;
    private javax.swing.JLabel lblTipoCU;
    private javax.swing.JLabel lblTituloOS;
    private javax.swing.JList<String> listFuente;
    private javax.swing.JMenuBar mBarPrincipal;
    private javax.swing.JMenuItem mItemColorLetraNavbar;
    private javax.swing.JMenuItem mItemCrearUsuario;
    private javax.swing.JMenuItem mItemEditarUsuario;
    private javax.swing.JMenuItem mItemEliminarUsuario;
    private javax.swing.JMenuItem mItemFondoColor;
    private javax.swing.JMenuItem mItemFondoImagen;
    private javax.swing.JMenuItem mItemFuente;
    private javax.swing.JMenuItem mItemNavbarColor;
    private javax.swing.JMenu menuApagar;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuOpcionesUsuario;
    private javax.swing.JMenu menuPersonalizar;
    private javax.swing.JPanel panelEditorTexto;
    private javax.swing.JPanel panelInicioOS;
    private javax.swing.JPanel panelInicioSesion;
    private javax.swing.JToggleButton tgBtnTitulo;
    private javax.swing.JTextArea txtAreaEditorTexto;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtContrasenaCU;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCU;
    // End of variables declaration//GEN-END:variables
}
