
package proyectofinalp2_davidcastro;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    
    // Mis Atributos
    private String [] fuentes;
    private ArrayList<Usuario> usuarios = new ArrayList<Usuario>();
    private DefaultListModel modeloListaFuentes = new DefaultListModel();
    private DefaultListModel modeloListaUsuarios = new DefaultListModel();
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private DateTimeFormatter formato = DateTimeFormatter.ofPattern("hh:mm a");
    
    public PantallaPrincipal() {
        
        usuarios.add(new Administrador("admin", "1234"));
        fuentes = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
        
        initComponents();
        
        tablaUsuarioInfoSistema.setModel(modeloTabla);
        modeloTabla.addColumn("Usuario Actual");
        modeloTabla.addColumn("Hora");
        modeloTabla.addColumn("Fecha");
        modeloTabla.setRowCount(1);
        
        modeloListaUsuarios.addElement(usuarios.get(0));
        listFuente.setModel(modeloListaFuentes);
        listUsuariosRegistrados.setModel(modeloListaUsuarios);
        agregarElementos();
        setLocationRelativeTo(null);
        //System.out.println(usuarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framePantallaInicioOS = new javax.swing.JFrame();
        panelInicioOS = new javax.swing.JPanel();
        lblIconoEditorTextoOS = new javax.swing.JLabel();
        lblEditorTextoOS = new javax.swing.JLabel();
        lblIconoExploradorArchivosOS = new javax.swing.JLabel();
        lblExploradorArchivoOS = new javax.swing.JLabel();
        lblTituloOS = new javax.swing.JLabel();
        lblIconoInfoSistemaOS = new javax.swing.JLabel();
        lblInfoSistemaOS = new javax.swing.JLabel();
        mBarPrincipal = new javax.swing.JMenuBar();
        menuOpcionesUsuario = new javax.swing.JMenu();
        mItemCrearUsuario = new javax.swing.JMenuItem();
        mItemEditarUsuario = new javax.swing.JMenuItem();
        mItemEliminarUsuario = new javax.swing.JMenuItem();
        menuPersonalizar = new javax.swing.JMenu();
        mItemNavbarColor = new javax.swing.JMenuItem();
        mItemColorLetraNavbar = new javax.swing.JMenuItem();
        mItemFondoColor = new javax.swing.JMenuItem();
        mItemFuente = new javax.swing.JMenuItem();
        mItemFondoImagen = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();
        menuApagar = new javax.swing.JMenu();
        dialCrearUsuario = new javax.swing.JDialog();
        lblTituloCrearUsuario = new javax.swing.JLabel();
        lblContrasenaCU = new javax.swing.JLabel();
        lblNombreCU = new javax.swing.JLabel();
        txtContrasenaCU = new javax.swing.JTextField();
        txtNombreCU = new javax.swing.JTextField();
        lblTipoCU = new javax.swing.JLabel();
        comboTipoCU = new javax.swing.JComboBox<>();
        btnAtrasCU = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JButton();
        lblIconoCrearUsuario = new javax.swing.JLabel();
        dialEditorTexto = new javax.swing.JDialog();
        panelEditorTexto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEditorTexto = new javax.swing.JTextArea();
        btnAtrasEditorTexto = new javax.swing.JButton();
        comboTamano = new javax.swing.JComboBox<>();
        comboFuentes = new javax.swing.JComboBox<>();
        comboEstilos = new javax.swing.JComboBox<>();
        lblTamano = new javax.swing.JLabel();
        lblFuente = new javax.swing.JLabel();
        lblEstilo = new javax.swing.JLabel();
        btnColorEditorTexto = new javax.swing.JButton();
        lblColorEditorTexto = new javax.swing.JLabel();
        lblFondoEditorTexto = new javax.swing.JLabel();
        mBarEditorTexto = new javax.swing.JMenuBar();
        menuArchivoEditorTexto = new javax.swing.JMenu();
        mItemAbrirEditorTexto = new javax.swing.JMenuItem();
        mItemGuardarEditorTexto = new javax.swing.JMenuItem();
        dialPersonalizarFuente = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        listFuente = new javax.swing.JList<>();
        lblTituloPersonalizacionFuente = new javax.swing.JLabel();
        comboTamanoFuente = new javax.swing.JComboBox<>();
        comboEstiloFuente = new javax.swing.JComboBox<>();
        lblTamanoFuente = new javax.swing.JLabel();
        lblEstiloFuente = new javax.swing.JLabel();
        lblFuenteFuente = new javax.swing.JLabel();
        btnVolverFuente = new javax.swing.JButton();
        btnColorFuente = new javax.swing.JButton();
        tgBtnTitulo = new javax.swing.JToggleButton();
        lblOnOff = new javax.swing.JLabel();
        lblColorFuente = new javax.swing.JLabel();
        lblFondoFuente = new javax.swing.JLabel();
        dialInfoSistema = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaUsuarioInfoSistema = new javax.swing.JTable();
        lblTituloInfoSistema = new javax.swing.JLabel();
        btnEliminarUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        lblUsuariosRegistrados = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listUsuariosRegistrados = new javax.swing.JList<>();
        lblFondoInfoSistema = new javax.swing.JLabel();
        dialEditarUsuario = new javax.swing.JDialog();
        lblEditarUsuario = new javax.swing.JLabel();
        lblContrasenaEU = new javax.swing.JLabel();
        lblNombreEU = new javax.swing.JLabel();
        txtContrasenaEU = new javax.swing.JTextField();
        txtNombreEU = new javax.swing.JTextField();
        btnAceptarEU = new javax.swing.JButton();
        btnAtrasEU = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dialProgressBar = new javax.swing.JDialog();
        pBarCarga = new javax.swing.JProgressBar();
        panelInicioSesion = new javax.swing.JPanel();
        lblInicioSesion = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPassContrasena = new javax.swing.JPasswordField();
        lblFondo = new javax.swing.JLabel();

        framePantallaInicioOS.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                framePantallaInicioOSWindowClosed(evt);
            }
        });
        framePantallaInicioOS.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInicioOS.setBackground(new java.awt.Color(153, 153, 153));
        panelInicioOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoEditorTextoOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editor de texto.png"))); // NOI18N
        lblIconoEditorTextoOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconoEditorTextoOS.setOpaque(true);
        lblIconoEditorTextoOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconoEditorTextoOSMouseClicked(evt);
            }
        });
        panelInicioOS.add(lblIconoEditorTextoOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 140, 140));

        lblEditorTextoOS.setFont(new java.awt.Font("Calibri", 1, 23)); // NOI18N
        lblEditorTextoOS.setForeground(new java.awt.Color(0, 0, 0));
        lblEditorTextoOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditorTextoOS.setText("Editor de Texto");
        panelInicioOS.add(lblEditorTextoOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 230, 70));

        lblIconoExploradorArchivosOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/explorador archivos.png"))); // NOI18N
        lblIconoExploradorArchivosOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelInicioOS.add(lblIconoExploradorArchivosOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 140, 140));

        lblExploradorArchivoOS.setFont(new java.awt.Font("Calibri", 1, 23)); // NOI18N
        lblExploradorArchivoOS.setForeground(new java.awt.Color(0, 0, 0));
        lblExploradorArchivoOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExploradorArchivoOS.setText("Explorador de Archivos");
        panelInicioOS.add(lblExploradorArchivoOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 300, 70));

        lblTituloOS.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        lblTituloOS.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloOS.setText("Pantalla de Inicio");
        panelInicioOS.add(lblTituloOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 790, 100));

        lblIconoInfoSistemaOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono info de sistema.png"))); // NOI18N
        lblIconoInfoSistemaOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconoInfoSistemaOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconoInfoSistemaOSMouseClicked(evt);
            }
        });
        panelInicioOS.add(lblIconoInfoSistemaOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 140, 140));

        lblInfoSistemaOS.setFont(new java.awt.Font("Calibri", 1, 23)); // NOI18N
        lblInfoSistemaOS.setForeground(new java.awt.Color(0, 0, 0));
        lblInfoSistemaOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoSistemaOS.setText("Informacion del sistema");
        panelInicioOS.add(lblInfoSistemaOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 300, 70));

        framePantallaInicioOS.getContentPane().add(panelInicioOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        mBarPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 241, 241), 1, true));
        mBarPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mBarPrincipal.setOpaque(true);

        menuOpcionesUsuario.setForeground(new java.awt.Color(0, 0, 0));
        menuOpcionesUsuario.setText("Opciones de Usuario");
        menuOpcionesUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuOpcionesUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuOpcionesUsuario.setOpaque(true);
        menuOpcionesUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuOpcionesUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuOpcionesUsuarioMouseExited(evt);
            }
        });

        mItemCrearUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemCrearUsuario.setForeground(new java.awt.Color(0, 0, 0));
        mItemCrearUsuario.setText("Crear Usuario");
        mItemCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemCrearUsuario.setOpaque(true);
        mItemCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCrearUsuarioActionPerformed(evt);
            }
        });
        menuOpcionesUsuario.add(mItemCrearUsuario);

        mItemEditarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemEditarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        mItemEditarUsuario.setText("Editar Usuario");
        mItemEditarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemEditarUsuario.setOpaque(true);
        mItemEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemEditarUsuarioActionPerformed(evt);
            }
        });
        menuOpcionesUsuario.add(mItemEditarUsuario);

        mItemEliminarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemEliminarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        mItemEliminarUsuario.setText("Eliminar Usuario");
        mItemEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemEliminarUsuario.setOpaque(true);
        mItemEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemEliminarUsuarioActionPerformed(evt);
            }
        });
        menuOpcionesUsuario.add(mItemEliminarUsuario);

        mBarPrincipal.add(menuOpcionesUsuario);

        menuPersonalizar.setForeground(new java.awt.Color(0, 0, 0));
        menuPersonalizar.setText("Personalizar");
        menuPersonalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPersonalizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuPersonalizar.setOpaque(true);
        menuPersonalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPersonalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPersonalizarMouseExited(evt);
            }
        });

        mItemNavbarColor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemNavbarColor.setForeground(new java.awt.Color(0, 0, 0));
        mItemNavbarColor.setText("Color de la barra de navegacion");
        mItemNavbarColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemNavbarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemNavbarColorActionPerformed(evt);
            }
        });
        menuPersonalizar.add(mItemNavbarColor);

        mItemColorLetraNavbar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemColorLetraNavbar.setForeground(new java.awt.Color(0, 0, 0));
        mItemColorLetraNavbar.setText("Color de letra de la barra de navegacion");
        mItemColorLetraNavbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemColorLetraNavbarActionPerformed(evt);
            }
        });
        menuPersonalizar.add(mItemColorLetraNavbar);

        mItemFondoColor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemFondoColor.setForeground(new java.awt.Color(0, 0, 0));
        mItemFondoColor.setText("Color del fondo de pantalla");
        mItemFondoColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemFondoColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemFondoColorActionPerformed(evt);
            }
        });
        menuPersonalizar.add(mItemFondoColor);

        mItemFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemFuente.setForeground(new java.awt.Color(0, 0, 0));
        mItemFuente.setText("Fuente del fondo de pantalla");
        mItemFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemFuenteActionPerformed(evt);
            }
        });
        menuPersonalizar.add(mItemFuente);

        mItemFondoImagen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemFondoImagen.setForeground(new java.awt.Color(0, 0, 0));
        mItemFondoImagen.setText("Fondo de pantalla");
        mItemFondoImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemFondoImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemFondoImagenActionPerformed(evt);
            }
        });
        menuPersonalizar.add(mItemFondoImagen);

        mBarPrincipal.add(menuPersonalizar);

        menuLogout.setForeground(new java.awt.Color(0, 0, 0));
        menuLogout.setText("Logout");
        menuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuLogout.setOpaque(true);
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLogoutMouseExited(evt);
            }
        });
        mBarPrincipal.add(menuLogout);

        menuApagar.setForeground(new java.awt.Color(0, 0, 0));
        menuApagar.setText("Apagar");
        menuApagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuApagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuApagar.setOpaque(true);
        menuApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuApagarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuApagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuApagarMouseExited(evt);
            }
        });
        mBarPrincipal.add(menuApagar);

        framePantallaInicioOS.setJMenuBar(mBarPrincipal);

        dialCrearUsuario.setBackground(new java.awt.Color(102, 102, 102));
        dialCrearUsuario.setModal(true);
        dialCrearUsuario.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dialCrearUsuarioWindowClosed(evt);
            }
        });
        dialCrearUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloCrearUsuario.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTituloCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloCrearUsuario.setText("Crear Usuario");
        dialCrearUsuario.getContentPane().add(lblTituloCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 240, 50));

        lblContrasenaCU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblContrasenaCU.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasenaCU.setText("Contraseña:");
        dialCrearUsuario.getContentPane().add(lblContrasenaCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 25));

        lblNombreCU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreCU.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCU.setText("Nombre:");
        dialCrearUsuario.getContentPane().add(lblNombreCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 25));

        txtContrasenaCU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtContrasenaCU.setForeground(new java.awt.Color(0, 0, 0));
        txtContrasenaCU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dialCrearUsuario.getContentPane().add(txtContrasenaCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 250, 30));

        txtNombreCU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombreCU.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreCU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dialCrearUsuario.getContentPane().add(txtNombreCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 250, 30));

        lblTipoCU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoCU.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoCU.setText("Tipo:");
        dialCrearUsuario.getContentPane().add(lblTipoCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 50, 25));

        comboTipoCU.setBackground(new java.awt.Color(255, 255, 255));
        comboTipoCU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboTipoCU.setForeground(new java.awt.Color(0, 0, 0));
        comboTipoCU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Invitado" }));
        comboTipoCU.setSelectedIndex(-1);
        comboTipoCU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        comboTipoCU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboTipoCU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboTipoCUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comboTipoCUMouseExited(evt);
            }
        });
        dialCrearUsuario.getContentPane().add(comboTipoCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 160, 30));

        btnAtrasCU.setBackground(new java.awt.Color(153, 0, 0));
        btnAtrasCU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtrasCU.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasCU.setText("Atras");
        btnAtrasCU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtrasCU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtrasCU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtrasCUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtrasCUMouseExited(evt);
            }
        });
        btnAtrasCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasCUActionPerformed(evt);
            }
        });
        dialCrearUsuario.getContentPane().add(btnAtrasCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 60, 30));

        btnCrearUsuario.setBackground(new java.awt.Color(0, 0, 0));
        btnCrearUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearUsuario.setText("Crear Usuario");
        btnCrearUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseExited(evt);
            }
        });
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });
        dialCrearUsuario.getContentPane().add(btnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 140, 40));

        lblIconoCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo login.jpg"))); // NOI18N
        dialCrearUsuario.getContentPane().add(lblIconoCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 470));

        dialEditorTexto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEditorTexto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaEditorTexto.setColumns(20);
        txtAreaEditorTexto.setRows(5);
        jScrollPane1.setViewportView(txtAreaEditorTexto);

        panelEditorTexto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 596, 620));

        btnAtrasEditorTexto.setBackground(new java.awt.Color(153, 0, 0));
        btnAtrasEditorTexto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtrasEditorTexto.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasEditorTexto.setText("Atras");
        btnAtrasEditorTexto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtrasEditorTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtrasEditorTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasEditorTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtrasEditorTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtrasEditorTextoMouseExited(evt);
            }
        });
        panelEditorTexto.add(btnAtrasEditorTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 70, -1));

        comboTamano.setBackground(new java.awt.Color(75, 75, 75));
        comboTamano.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboTamano.setForeground(new java.awt.Color(255, 255, 255));
        comboTamano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        comboTamano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboTamano.setOpaque(true);
        comboTamano.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTamanoItemStateChanged(evt);
            }
        });
        panelEditorTexto.add(comboTamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 150, 25));

        comboFuentes.setBackground(new java.awt.Color(75, 75, 75));
        comboFuentes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboFuentes.setForeground(new java.awt.Color(255, 255, 255));
        comboFuentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        comboFuentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboFuentes.setOpaque(true);
        comboFuentes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFuentesItemStateChanged(evt);
            }
        });
        panelEditorTexto.add(comboFuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, 25));

        comboEstilos.setBackground(new java.awt.Color(75, 75, 75));
        comboEstilos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboEstilos.setForeground(new java.awt.Color(255, 255, 255));
        comboEstilos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Normal", "Negrita", "Cursiva" }));
        comboEstilos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboEstilos.setOpaque(true);
        comboEstilos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEstilosItemStateChanged(evt);
            }
        });
        panelEditorTexto.add(comboEstilos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, 25));

        lblTamano.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTamano.setForeground(new java.awt.Color(0, 0, 0));
        lblTamano.setText("Tamaño de letra");
        panelEditorTexto.add(lblTamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, -1));

        lblFuente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFuente.setForeground(new java.awt.Color(0, 0, 0));
        lblFuente.setText("Fuentes");
        panelEditorTexto.add(lblFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, -1));

        lblEstilo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstilo.setForeground(new java.awt.Color(0, 0, 0));
        lblEstilo.setText("Estilo de letra");
        panelEditorTexto.add(lblEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 20));

        btnColorEditorTexto.setBackground(new java.awt.Color(75, 75, 75));
        btnColorEditorTexto.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnColorEditorTexto.setForeground(new java.awt.Color(255, 255, 255));
        btnColorEditorTexto.setText("Escoger Color");
        btnColorEditorTexto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnColorEditorTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnColorEditorTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColorEditorTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnColorEditorTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnColorEditorTextoMouseExited(evt);
            }
        });
        panelEditorTexto.add(btnColorEditorTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 150, 25));

        lblColorEditorTexto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblColorEditorTexto.setForeground(new java.awt.Color(0, 0, 0));
        lblColorEditorTexto.setText("Color de Letra");
        panelEditorTexto.add(lblColorEditorTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 130, -1));

        lblFondoEditorTexto.setBackground(new java.awt.Color(153, 153, 153));
        lblFondoEditorTexto.setOpaque(true);
        panelEditorTexto.add(lblFondoEditorTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 640));

        dialEditorTexto.getContentPane().add(panelEditorTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 860, 640));

        menuArchivoEditorTexto.setForeground(new java.awt.Color(0, 0, 0));
        menuArchivoEditorTexto.setText("Archivo");
        menuArchivoEditorTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuArchivoEditorTexto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mItemAbrirEditorTexto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemAbrirEditorTexto.setForeground(new java.awt.Color(0, 0, 0));
        mItemAbrirEditorTexto.setText("Abrir");
        mItemAbrirEditorTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemAbrirEditorTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAbrirEditorTextoActionPerformed(evt);
            }
        });
        menuArchivoEditorTexto.add(mItemAbrirEditorTexto);

        mItemGuardarEditorTexto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mItemGuardarEditorTexto.setForeground(new java.awt.Color(0, 0, 0));
        mItemGuardarEditorTexto.setText("Guardar");
        mItemGuardarEditorTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mItemGuardarEditorTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemGuardarEditorTextoActionPerformed(evt);
            }
        });
        menuArchivoEditorTexto.add(mItemGuardarEditorTexto);

        mBarEditorTexto.add(menuArchivoEditorTexto);

        dialEditorTexto.setJMenuBar(mBarEditorTexto);

        dialPersonalizarFuente.setModal(true);
        dialPersonalizarFuente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listFuente.setBackground(new java.awt.Color(75, 75, 75));
        listFuente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listFuente.setForeground(new java.awt.Color(255, 255, 255));
        listFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listFuente.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listFuenteValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listFuente);

        dialPersonalizarFuente.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, 110));

        lblTituloPersonalizacionFuente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloPersonalizacionFuente.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPersonalizacionFuente.setText("Personalizacion de Fuente");
        dialPersonalizarFuente.getContentPane().add(lblTituloPersonalizacionFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 300, 35));

        comboTamanoFuente.setBackground(new java.awt.Color(75, 75, 75));
        comboTamanoFuente.setForeground(new java.awt.Color(255, 255, 255));
        comboTamanoFuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        comboTamanoFuente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 75, 75)));
        comboTamanoFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboTamanoFuente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTamanoFuenteItemStateChanged(evt);
            }
        });
        dialPersonalizarFuente.getContentPane().add(comboTamanoFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, -1));

        comboEstiloFuente.setBackground(new java.awt.Color(75, 75, 75));
        comboEstiloFuente.setForeground(new java.awt.Color(255, 255, 255));
        comboEstiloFuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Normal", "Negrita", "Cursiva" }));
        comboEstiloFuente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 75, 75)));
        comboEstiloFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboEstiloFuente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEstiloFuenteItemStateChanged(evt);
            }
        });
        dialPersonalizarFuente.getContentPane().add(comboEstiloFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, -1));

        lblTamanoFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTamanoFuente.setForeground(new java.awt.Color(255, 255, 255));
        lblTamanoFuente.setText("Tamano de letra");
        dialPersonalizarFuente.getContentPane().add(lblTamanoFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, -1));

        lblEstiloFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstiloFuente.setForeground(new java.awt.Color(255, 255, 255));
        lblEstiloFuente.setText("Estilo de letra");
        dialPersonalizarFuente.getContentPane().add(lblEstiloFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, -1));

        lblFuenteFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFuenteFuente.setForeground(new java.awt.Color(255, 255, 255));
        lblFuenteFuente.setText("Fuente");
        dialPersonalizarFuente.getContentPane().add(lblFuenteFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 100, -1));

        btnVolverFuente.setBackground(new java.awt.Color(153, 0, 0));
        btnVolverFuente.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnVolverFuente.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverFuente.setText("Volver");
        btnVolverFuente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolverFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverFuente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverFuenteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverFuenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverFuenteMouseExited(evt);
            }
        });
        dialPersonalizarFuente.getContentPane().add(btnVolverFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, -1));

        btnColorFuente.setBackground(new java.awt.Color(75, 75, 75));
        btnColorFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnColorFuente.setForeground(new java.awt.Color(255, 255, 255));
        btnColorFuente.setText("Escoger Color");
        btnColorFuente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnColorFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnColorFuente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColorFuenteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnColorFuenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnColorFuenteMouseExited(evt);
            }
        });
        dialPersonalizarFuente.getContentPane().add(btnColorFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 23));

        tgBtnTitulo.setBackground(new java.awt.Color(75, 75, 75));
        tgBtnTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tgBtnTitulo.setForeground(new java.awt.Color(255, 255, 255));
        tgBtnTitulo.setText("Hacer cambios al Titulo");
        tgBtnTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tgBtnTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tgBtnTitulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tgBtnTituloItemStateChanged(evt);
            }
        });
        dialPersonalizarFuente.getContentPane().add(tgBtnTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 223, 160, 30));

        lblOnOff.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblOnOff.setForeground(new java.awt.Color(255, 0, 0));
        lblOnOff.setText("OFF");
        dialPersonalizarFuente.getContentPane().add(lblOnOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 60, 30));

        lblColorFuente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblColorFuente.setForeground(new java.awt.Color(255, 255, 255));
        lblColorFuente.setText("Color de letra");
        dialPersonalizarFuente.getContentPane().add(lblColorFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, -1));

        lblFondoFuente.setBackground(new java.awt.Color(51, 51, 51));
        lblFondoFuente.setOpaque(true);
        dialPersonalizarFuente.getContentPane().add(lblFondoFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 270));

        dialInfoSistema.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaUsuarioInfoSistema.setBackground(new java.awt.Color(204, 204, 204));
        tablaUsuarioInfoSistema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablaUsuarioInfoSistema.setForeground(new java.awt.Color(0, 0, 0));
        tablaUsuarioInfoSistema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane3.setViewportView(tablaUsuarioInfoSistema);

        dialInfoSistema.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 310, 40));

        lblTituloInfoSistema.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloInfoSistema.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloInfoSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloInfoSistema.setText("Informacion del Sistema");
        dialInfoSistema.getContentPane().add(lblTituloInfoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 320, 40));

        btnEliminarUsuario.setBackground(new java.awt.Color(75, 75, 75));
        btnEliminarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUsuario.setText("Eliminar Usuario");
        btnEliminarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarUsuario.setPreferredSize(new java.awt.Dimension(122, 26));
        btnEliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarUsuarioMouseExited(evt);
            }
        });
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });
        dialInfoSistema.getContentPane().add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        btnEditarUsuario.setBackground(new java.awt.Color(75, 75, 75));
        btnEditarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarUsuario.setText("Editar Usuario");
        btnEditarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarUsuario.setPreferredSize(new java.awt.Dimension(109, 26));
        btnEditarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarUsuarioMouseExited(evt);
            }
        });
        dialInfoSistema.getContentPane().add(btnEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        lblUsuariosRegistrados.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUsuariosRegistrados.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuariosRegistrados.setText("Lista de Usuarios registrados en el sistema");
        dialInfoSistema.getContentPane().add(lblUsuariosRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        listUsuariosRegistrados.setBackground(new java.awt.Color(204, 204, 204));
        listUsuariosRegistrados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listUsuariosRegistrados.setForeground(new java.awt.Color(0, 0, 0));
        listUsuariosRegistrados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane4.setViewportView(listUsuariosRegistrados);

        dialInfoSistema.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 250, 130));

        lblFondoInfoSistema.setBackground(new java.awt.Color(51, 51, 51));
        lblFondoInfoSistema.setForeground(new java.awt.Color(246, 245, 245));
        lblFondoInfoSistema.setOpaque(true);
        dialInfoSistema.getContentPane().add(lblFondoInfoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 390));

        dialEditarUsuario.setModal(true);
        dialEditarUsuario.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dialEditarUsuarioWindowClosed(evt);
            }
        });
        dialEditarUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEditarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblEditarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditarUsuario.setText("Editar Usuario");
        dialEditarUsuario.getContentPane().add(lblEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 190, -1));

        lblContrasenaEU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblContrasenaEU.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasenaEU.setText("Contraseña:");
        dialEditarUsuario.getContentPane().add(lblContrasenaEU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, -1));

        lblNombreEU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreEU.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreEU.setText("Nombre:");
        dialEditarUsuario.getContentPane().add(lblNombreEU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 60, -1));

        txtContrasenaEU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtContrasenaEU.setForeground(new java.awt.Color(0, 0, 0));
        txtContrasenaEU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dialEditarUsuario.getContentPane().add(txtContrasenaEU, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 220, 25));

        txtNombreEU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombreEU.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreEU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dialEditarUsuario.getContentPane().add(txtNombreEU, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 220, 25));

        btnAceptarEU.setBackground(new java.awt.Color(75, 75, 75));
        btnAceptarEU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAceptarEU.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarEU.setText("Aceptar");
        btnAceptarEU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAceptarEU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptarEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarEUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarEUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarEUMouseExited(evt);
            }
        });
        dialEditarUsuario.getContentPane().add(btnAceptarEU, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, 25));

        btnAtrasEU.setBackground(new java.awt.Color(153, 0, 0));
        btnAtrasEU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtrasEU.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasEU.setText("Atras");
        btnAtrasEU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtrasEU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtrasEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasEUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtrasEUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtrasEUMouseExited(evt);
            }
        });
        dialEditarUsuario.getContentPane().add(btnAtrasEU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 70, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo login.jpg"))); // NOI18N
        dialEditarUsuario.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 392, 286));

        pBarCarga.setBackground(new java.awt.Color(75, 75, 75));
        pBarCarga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pBarCarga.setForeground(new java.awt.Color(0, 0, 102));
        pBarCarga.setOpaque(true);
        pBarCarga.setStringPainted(true);

        javax.swing.GroupLayout dialProgressBarLayout = new javax.swing.GroupLayout(dialProgressBar.getContentPane());
        dialProgressBar.getContentPane().setLayout(dialProgressBarLayout);
        dialProgressBarLayout.setHorizontalGroup(
            dialProgressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialProgressBarLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(pBarCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        dialProgressBarLayout.setVerticalGroup(
            dialProgressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialProgressBarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(pBarCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInicioSesion.setPreferredSize(new java.awt.Dimension(507, 600));
        panelInicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblInicioSesion.setText("Inicio de sesion");
        panelInicioSesion.add(lblInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 260, -1));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono inicio sesion.jpg"))); // NOI18N
        panelInicioSesion.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        lblContrasena.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contraseña:");
        panelInicioSesion.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 30));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        panelInicioSesion.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 30));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelInicioSesion.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 250, 30));

        btnIniciarSesion.setBackground(new java.awt.Color(0, 0, 0));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar sesion");
        btnIniciarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseExited(evt);
            }
        });
        panelInicioSesion.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 130, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Si es primera vez, utiliza (Nombre = admin / Contraseña = 1234) para poder entrar.");
        panelInicioSesion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 470, -1));

        txtPassContrasena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPassContrasena.setForeground(new java.awt.Color(0, 0, 0));
        txtPassContrasena.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelInicioSesion.add(txtPassContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 392, 250, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo login.jpg"))); // NOI18N
        panelInicioSesion.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    String nombre = "", contrasena = ""; 
    Usuario usuarioAct = new Usuario();
    private void btnIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseClicked
        nombre = txtNombre.getText();
        contrasena = new String(txtPassContrasena.getPassword());
        if (verificarUsuario(nombre, contrasena)){
            usuarioAct = usuarioActual(nombre, contrasena);
            txtNombre.setText("");
            txtPassContrasena.setText("");
            
            barraDeProgreso(framePantallaInicioOS);
            dispose();
            //JOptionPane.showMessageDialog(this, "Sesion iniciada");
        } else {
            JOptionPane.showMessageDialog(this, "No existe ese usuario","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        if (usuarioActual(nombre, contrasena) instanceof Invitado) {
            menuOpcionesUsuario.setVisible(false);
            btnEliminarUsuario.setVisible(false);
            btnEditarUsuario.setVisible(false);
        } else {
            menuOpcionesUsuario.setVisible(true);
            btnEliminarUsuario.setVisible(true);
            btnEditarUsuario.setVisible(true);
        }
    }//GEN-LAST:event_btnIniciarSesionMouseClicked

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estas seguro que quieres cerrar sesion?", "Advertencia", JOptionPane.YES_NO_CANCEL_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            framePantallaInicioOS.dispose();
            barraDeProgreso(this);
        }
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void btnAtrasEditorTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasEditorTextoMouseClicked
        dialEditorTexto.dispose();
        //framePantallaInicioOS.setVisible(true);
    }//GEN-LAST:event_btnAtrasEditorTextoMouseClicked

    private void comboTamanoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTamanoItemStateChanged
        if (!(comboTamano.getSelectedIndex() == 0)) {
            int tamano = Integer.parseInt(comboTamano.getSelectedItem()+"");
            String nombre = txtAreaEditorTexto.getFont().getFontName();
            int estilo = txtAreaEditorTexto.getFont().getStyle();
            txtAreaEditorTexto.setFont(new Font(nombre, estilo, tamano));
        } 
    }//GEN-LAST:event_comboTamanoItemStateChanged

    private void comboFuentesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFuentesItemStateChanged
        if (!(comboFuentes.getSelectedIndex() == 0)) {
            int tamano = txtAreaEditorTexto.getFont().getSize();
            String nombre = comboFuentes.getSelectedItem()+"";
            int estilo = txtAreaEditorTexto.getFont().getStyle();
            txtAreaEditorTexto.setFont(new Font(nombre, estilo, tamano));
        }
    }//GEN-LAST:event_comboFuentesItemStateChanged

    private void comboEstilosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEstilosItemStateChanged
        int tamano = txtAreaEditorTexto.getFont().getSize();
        String nombre = txtAreaEditorTexto.getFont().getFontName();
        int estilo = comboEstilos.getSelectedIndex();
        switch (estilo){
            case 1:
                txtAreaEditorTexto.setFont(new Font(nombre, Font.PLAIN, tamano));
                break;
            case 2:
                txtAreaEditorTexto.setFont(new Font(nombre, Font.BOLD, tamano));
                break;
            case 3:
                txtAreaEditorTexto.setFont(new Font(nombre, Font.ITALIC, tamano));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_comboEstilosItemStateChanged

    private void btnAtrasCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasCUActionPerformed
        dialCrearUsuario.dispose();
    }//GEN-LAST:event_btnAtrasCUActionPerformed

    private void mItemCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCrearUsuarioActionPerformed
        barraDeProgreso(dialCrearUsuario);
    }//GEN-LAST:event_mItemCrearUsuarioActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        if ((txtNombreCU.getText().isBlank() && txtContrasenaCU.getText().isBlank() && comboTipoCU.getSelectedIndex() == -1) || txtNombreCU.getText().isBlank() || txtContrasenaCU.getText().isBlank() || comboTipoCU.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "No has ingresado los campos necesarios", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (comboTipoCU.getSelectedIndex() == 0) {
                usuarios.add(new Administrador(txtNombreCU.getText(), txtContrasenaCU.getText()));
                modeloListaUsuarios.addElement(new Administrador(txtNombreCU.getText(), txtContrasenaCU.getText()));
            } else {
                usuarios.add(new Invitado(txtNombreCU.getText(), txtContrasenaCU.getText()));
                modeloListaUsuarios.addElement(new Invitado(txtNombreCU.getText(), txtContrasenaCU.getText()));
            }
            JOptionPane.showMessageDialog(this, "Usuario creado exitosamente", "Crear Usuario", JOptionPane.INFORMATION_MESSAGE);
            dialCrearUsuario.dispose();
        }
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void lblIconoEditorTextoOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconoEditorTextoOSMouseClicked
        //framePantallaInicioOS.dispose();
        barraDeProgreso(dialEditorTexto);
    }//GEN-LAST:event_lblIconoEditorTextoOSMouseClicked

    private void menuApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuApagarMouseClicked
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estas seguro que quieres apagar el sistema operativo?", "Advertencia", JOptionPane.YES_NO_CANCEL_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuApagarMouseClicked
    
    Color colorSeleccionadoTemp;
    private void mItemNavbarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemNavbarColorActionPerformed
        Color colorSeleccionado = JColorChooser.showDialog(this, "Escoge el color de la barra de navegacion", Color.BLACK);
        mBarPrincipal.setBackground(colorSeleccionado);
        menuPersonalizar.setBackground(colorSeleccionado);
        menuApagar.setBackground(colorSeleccionado);
        menuLogout.setBackground(colorSeleccionado);
        menuOpcionesUsuario.setBackground(colorSeleccionado);
        colorSeleccionadoTemp = colorSeleccionado;
    }//GEN-LAST:event_mItemNavbarColorActionPerformed

    private void mItemFondoColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemFondoColorActionPerformed
        Color colorseleccionado = JColorChooser.showDialog(this, "Escoge el color del fondo", Color.BLACK);
        panelInicioOS.setBackground(colorseleccionado);
    }//GEN-LAST:event_mItemFondoColorActionPerformed

    private void btnIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseEntered
        btnIniciarSesion.setBackground(Color.decode("#444444"));
    }//GEN-LAST:event_btnIniciarSesionMouseEntered

    private void btnIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseExited
        btnIniciarSesion.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnIniciarSesionMouseExited

    private void menuOpcionesUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOpcionesUsuarioMouseEntered
        menuOpcionesUsuario.setBackground(Color.decode("#898989"));
    }//GEN-LAST:event_menuOpcionesUsuarioMouseEntered

    private void menuOpcionesUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOpcionesUsuarioMouseExited
        menuOpcionesUsuario.setBackground(colorSeleccionadoTemp);
    }//GEN-LAST:event_menuOpcionesUsuarioMouseExited

    private void menuPersonalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPersonalizarMouseEntered
        menuPersonalizar.setBackground(Color.decode("#898989"));
    }//GEN-LAST:event_menuPersonalizarMouseEntered

    private void menuPersonalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPersonalizarMouseExited
        menuPersonalizar.setBackground(colorSeleccionadoTemp);
    }//GEN-LAST:event_menuPersonalizarMouseExited

    private void menuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseEntered
        menuLogout.setBackground(Color.decode("#898989"));
    }//GEN-LAST:event_menuLogoutMouseEntered

    private void menuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseExited
        menuLogout.setBackground(colorSeleccionadoTemp);
    }//GEN-LAST:event_menuLogoutMouseExited

    private void menuApagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuApagarMouseEntered
        menuApagar.setBackground(Color.decode("#898989"));
    }//GEN-LAST:event_menuApagarMouseEntered

    private void menuApagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuApagarMouseExited
        menuApagar.setBackground(colorSeleccionadoTemp);
    }//GEN-LAST:event_menuApagarMouseExited

    private void comboTipoCUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTipoCUMouseEntered
        comboTipoCU.setBackground(Color.decode("#898989"));
    }//GEN-LAST:event_comboTipoCUMouseEntered

    private void comboTipoCUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTipoCUMouseExited
        comboTipoCU.setBackground(Color.WHITE);
    }//GEN-LAST:event_comboTipoCUMouseExited

    private void btnCrearUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseEntered
        btnCrearUsuario.setBackground(Color.decode("#444444"));
    }//GEN-LAST:event_btnCrearUsuarioMouseEntered

    private void btnCrearUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseExited
        btnCrearUsuario.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnCrearUsuarioMouseExited

    private void btnAtrasCUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasCUMouseEntered
        btnAtrasCU.setBackground(Color.decode("#5b0000"));
    }//GEN-LAST:event_btnAtrasCUMouseEntered

    private void btnAtrasCUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasCUMouseExited
        btnAtrasCU.setBackground(Color.decode("#990000"));
    }//GEN-LAST:event_btnAtrasCUMouseExited

    private void btnAtrasEditorTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasEditorTextoMouseEntered
        btnAtrasEditorTexto.setBackground(Color.decode("#5b0000"));
    }//GEN-LAST:event_btnAtrasEditorTextoMouseEntered

    private void btnAtrasEditorTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasEditorTextoMouseExited
        btnAtrasEditorTexto.setBackground(Color.decode("#990000"));
    }//GEN-LAST:event_btnAtrasEditorTextoMouseExited

    private void btnVolverFuenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverFuenteMouseClicked
        dialPersonalizarFuente.dispose();
    }//GEN-LAST:event_btnVolverFuenteMouseClicked

    private void mItemFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemFuenteActionPerformed
        dialPersonalizarFuente.pack();
        dialPersonalizarFuente.setLocationRelativeTo(this);
        dialPersonalizarFuente.setVisible(true);
    }//GEN-LAST:event_mItemFuenteActionPerformed

    private void comboTamanoFuenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTamanoFuenteItemStateChanged
        if (!(comboTamanoFuente.getSelectedIndex() == 0)) {
            int tamano = Integer.parseInt(comboTamanoFuente.getSelectedItem()+"");
            String nombre = lblEditorTextoOS.getFont().getFontName(), nombreTitulo = lblTituloOS.getFont().getFontName();
            int estilo = lblEditorTextoOS.getFont().getStyle(), estiloTitulo = lblTituloOS.getFont().getStyle();

            if (tgBtnTitulo.isSelected()) {
                lblTituloOS.setFont(new Font(nombreTitulo, estiloTitulo, tamano));
            } else {
                lblEditorTextoOS.setFont(new Font(nombre, estilo, tamano));
                lblExploradorArchivoOS.setFont(new Font(nombre, estilo, tamano));
                lblInfoSistemaOS.setFont(new Font(nombre, estilo, tamano));
            }
        }
    }//GEN-LAST:event_comboTamanoFuenteItemStateChanged

    private void btnColorFuenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorFuenteMouseEntered
        btnColorFuente.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnColorFuenteMouseEntered

    private void btnColorFuenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorFuenteMouseExited
        btnColorFuente.setBackground(Color.decode("#4B4B4B"));
    }//GEN-LAST:event_btnColorFuenteMouseExited

    private void btnVolverFuenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverFuenteMouseEntered
        btnVolverFuente.setBackground(Color.decode("#5b0000"));
    }//GEN-LAST:event_btnVolverFuenteMouseEntered

    private void btnVolverFuenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverFuenteMouseExited
        btnVolverFuente.setBackground(Color.decode("#990000"));
    }//GEN-LAST:event_btnVolverFuenteMouseExited

    private void btnColorFuenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorFuenteMouseClicked
        Color colorSeleccionado = JColorChooser.showDialog(this, "Escoge el color de la letra de la pantalla de inicio", Color.BLACK);
        if (tgBtnTitulo.isSelected()) {
            lblTituloOS.setForeground(colorSeleccionado);
        } else {
            lblEditorTextoOS.setForeground(colorSeleccionado);
            lblExploradorArchivoOS.setForeground(colorSeleccionado);
            lblInfoSistemaOS.setForeground(colorSeleccionado);
        }
    }//GEN-LAST:event_btnColorFuenteMouseClicked

    private void listFuenteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listFuenteValueChanged
        int tamano = lblEditorTextoOS.getFont().getSize(), tamanoTitulo = lblTituloOS.getFont().getSize();
        String nombre = listFuente.getSelectedValue();
        int estilo = lblEditorTextoOS.getFont().getStyle(), estiloTitulo = lblTituloOS.getFont().getStyle();
        
        if (tgBtnTitulo.isSelected()) {
            lblTituloOS.setFont(new Font(nombre, estiloTitulo, tamanoTitulo));
        } else {
            lblEditorTextoOS.setFont(new Font(nombre, estilo, tamano));
            lblExploradorArchivoOS.setFont(new Font(nombre, estilo, tamano));
            lblInfoSistemaOS.setFont(new Font(nombre, estilo, tamano));
        }
    }//GEN-LAST:event_listFuenteValueChanged

    private void comboEstiloFuenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEstiloFuenteItemStateChanged
        int tamano = lblEditorTextoOS.getFont().getSize(), tamanoTitulo = lblTituloOS.getFont().getSize();
        String nombre = lblEditorTextoOS.getFont().getFontName(), nombreTitulo = lblTituloOS.getFont().getFontName();
        int estilo = comboEstiloFuente.getSelectedIndex();
        
        if (tgBtnTitulo.isSelected()) {
            switch (estilo){
            case 1:
                lblTituloOS.setFont(new Font(nombreTitulo,Font.PLAIN,tamanoTitulo));
                break;
            case 2:
                lblTituloOS.setFont(new Font(nombreTitulo,Font.BOLD,tamanoTitulo));
                break;
            case 3:
                lblTituloOS.setFont(new Font(nombreTitulo,Font.ITALIC,tamanoTitulo));
                break;
            default:
                break;
            }
        } else {
            switch (estilo){
                case 1:
                    lblEditorTextoOS.setFont(new Font(nombre, Font.PLAIN, tamano));
                    lblExploradorArchivoOS.setFont(new Font(nombre, Font.PLAIN, tamano));
                    lblInfoSistemaOS.setFont(new Font(nombre, Font.PLAIN, tamano));
                    break;
                case 2:
                    lblEditorTextoOS.setFont(new Font(nombre, Font.BOLD, tamano));
                    lblExploradorArchivoOS.setFont(new Font(nombre, Font.BOLD, tamano));
                    lblInfoSistemaOS.setFont(new Font(nombre, Font.BOLD, tamano));
                    break;
                case 3:
                    lblEditorTextoOS.setFont(new Font(nombre, Font.ITALIC, tamano));
                    lblExploradorArchivoOS.setFont(new Font(nombre, Font.ITALIC, tamano));
                    lblInfoSistemaOS.setFont(new Font(nombre, Font.ITALIC, tamano));
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_comboEstiloFuenteItemStateChanged

    private void framePantallaInicioOSWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_framePantallaInicioOSWindowClosed
        //-----------------------------------------------------------------------------------------------------\\
    }//GEN-LAST:event_framePantallaInicioOSWindowClosed

    private void mItemColorLetraNavbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemColorLetraNavbarActionPerformed
        Color colorSeleccionado = JColorChooser.showDialog(this, "Escoge el color de la letra de la barra de navegacion", Color.BLACK);
        menuOpcionesUsuario.setForeground(colorSeleccionado);
        menuPersonalizar.setForeground(colorSeleccionado);
        menuLogout.setForeground(colorSeleccionado);
        menuApagar.setForeground(colorSeleccionado);
    }//GEN-LAST:event_mItemColorLetraNavbarActionPerformed

    private void tgBtnTituloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tgBtnTituloItemStateChanged
        if (tgBtnTitulo.isSelected()) {
            lblOnOff.setText("ON");
            lblOnOff.setForeground(Color.GREEN);
        } else {
            lblOnOff.setText("OFF");
            lblOnOff.setForeground(Color.RED);
        }
    }//GEN-LAST:event_tgBtnTituloItemStateChanged

    private void mItemFondoImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemFondoImagenActionPerformed
        //-----------------------------------------------------------------------------------\\
    }//GEN-LAST:event_mItemFondoImagenActionPerformed

    private void lblIconoInfoSistemaOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconoInfoSistemaOSMouseClicked
        modeloTabla.setValueAt(usuarioActual(nombre, contrasena).getNombre(), 0, 0);
        modeloTabla.setValueAt(LocalTime.now().format(formato), 0, 1);
        modeloTabla.setValueAt(LocalDate.now(), 0, 2);
        
        barraDeProgreso(dialInfoSistema);
    }//GEN-LAST:event_lblIconoInfoSistemaOSMouseClicked

        JFileChooser buscador = new JFileChooser();
    private void mItemAbrirEditorTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAbrirEditorTextoActionPerformed
        int opcion = buscador.showOpenDialog(this);
        
        if (opcion == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = buscador.getSelectedFile();
            try {
                BufferedReader br = new BufferedReader(new FileReader(archivoSeleccionado));
                String linea = "";
                txtAreaEditorTexto.setText("");
                do {
                    String lineaAnterior = txtAreaEditorTexto.getText();
                    linea =br.readLine();
                    if (linea != null) {
                        txtAreaEditorTexto.setText(lineaAnterior + "\n" + linea);
                    } 
                } while (linea != null);
                br.close();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Algo salio mal", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mItemAbrirEditorTextoActionPerformed

    private void mItemGuardarEditorTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemGuardarEditorTextoActionPerformed
        int opcion = buscador.showSaveDialog(this);
        
        if (opcion == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = buscador.getSelectedFile();
            
            try {
                BufferedWriter bw = new BufferedWriter(new FileWriter(archivoSeleccionado, false));
                bw.write(txtAreaEditorTexto.getText());
                bw.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Algo salio mal", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mItemGuardarEditorTextoActionPerformed

    private void btnColorEditorTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorEditorTextoMouseClicked
        Color colorSeleccionado = JColorChooser.showDialog(this, "Escoge el color de la letra del editor de texto", Color.BLACK);
        txtAreaEditorTexto.setForeground(colorSeleccionado);
    }//GEN-LAST:event_btnColorEditorTextoMouseClicked

    private void btnColorEditorTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorEditorTextoMouseEntered
        btnColorEditorTexto.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnColorEditorTextoMouseEntered

    private void btnColorEditorTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorEditorTextoMouseExited
        btnColorEditorTexto.setBackground(Color.decode("#4B4B4B"));
    }//GEN-LAST:event_btnColorEditorTextoMouseExited
    
    int seleccionado = 0; 
    private void btnEliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioMouseClicked
        seleccionado = listUsuariosRegistrados.getSelectedIndex();
        if (seleccionado == -1) {
            JOptionPane.showMessageDialog(this, "No has seleccionado un usuario\nSelecciona un usuario de la lista", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (usuarios.get(seleccionado).equals(usuarioAct)) {
            JOptionPane.showMessageDialog(this, "No puedes eliminar el usuario en el que estas actualmente", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            int opcion = JOptionPane.showConfirmDialog(this, "Estas seguro que deseas eliminar a " + ((Usuario) modeloListaUsuarios.getElementAt(seleccionado)).getNombre() , "Eliminar Usuario", JOptionPane.YES_NO_CANCEL_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                modeloListaUsuarios.removeElementAt(seleccionado);
                usuarios.remove(seleccionado);
            }
        }
    }//GEN-LAST:event_btnEliminarUsuarioMouseClicked

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed

    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnEliminarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioMouseEntered
        btnEliminarUsuario.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnEliminarUsuarioMouseEntered

    private void btnEliminarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioMouseExited
        btnEliminarUsuario.setBackground(Color.decode("#4B4B4B"));
    }//GEN-LAST:event_btnEliminarUsuarioMouseExited

    private void btnEditarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarUsuarioMouseClicked
        seleccionado = listUsuariosRegistrados.getSelectedIndex();
        if (seleccionado == -1) {
            JOptionPane.showMessageDialog(this, "No has seleccionado un usuario\nSelecciona un usuario de la lista", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            barraDeProgreso(dialEditarUsuario);
        } 
    }//GEN-LAST:event_btnEditarUsuarioMouseClicked

    private void btnAceptarEUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarEUMouseClicked
        nombre = txtNombreEU.getText();
        contrasena = txtContrasenaEU.getText();
        usuarios.get(seleccionado).setNombre(nombre);
        usuarios.get(seleccionado).setContrasena(contrasena);
        modeloListaUsuarios.set(seleccionado, usuarios.get(seleccionado));
        
        JOptionPane.showMessageDialog(this, "Usuario editado correctamente", "Editar Usuario", JOptionPane.INFORMATION_MESSAGE);
        dialEditarUsuario.dispose();
    }//GEN-LAST:event_btnAceptarEUMouseClicked

    private void btnAtrasEUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasEUMouseClicked
        dialEditarUsuario.dispose();
    }//GEN-LAST:event_btnAtrasEUMouseClicked

    private void dialEditarUsuarioWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialEditarUsuarioWindowClosed
        txtNombreEU.setText(""); txtContrasenaEU.setText("");
    }//GEN-LAST:event_dialEditarUsuarioWindowClosed

    private void dialCrearUsuarioWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialCrearUsuarioWindowClosed
        txtNombreCU.setText(""); txtContrasenaCU.setText("");
    }//GEN-LAST:event_dialCrearUsuarioWindowClosed

    private void btnAceptarEUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarEUMouseEntered
        btnAceptarEU.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnAceptarEUMouseEntered

    private void btnAceptarEUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarEUMouseExited
        btnAceptarEU.setBackground(Color.decode("#4B4B4B"));
    }//GEN-LAST:event_btnAceptarEUMouseExited

    private void btnAtrasEUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasEUMouseEntered
        btnAtrasEU.setBackground(Color.decode("#5b0000"));
    }//GEN-LAST:event_btnAtrasEUMouseEntered

    private void btnAtrasEUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasEUMouseExited
        btnAtrasEU.setBackground(Color.decode("#990000"));
    }//GEN-LAST:event_btnAtrasEUMouseExited

    private void mItemEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemEditarUsuarioActionPerformed
        barraDeProgreso(dialInfoSistema);
    }//GEN-LAST:event_mItemEditarUsuarioActionPerformed

    private void mItemEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemEliminarUsuarioActionPerformed
        barraDeProgreso(dialInfoSistema);
    }//GEN-LAST:event_mItemEliminarUsuarioActionPerformed

    private void btnEditarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarUsuarioMouseEntered
        btnEditarUsuario.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnEditarUsuarioMouseEntered

    private void btnEditarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarUsuarioMouseExited
        btnEditarUsuario.setBackground(Color.decode("#4B4B4B"));
    }//GEN-LAST:event_btnEditarUsuarioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }
    
    private boolean verificarUsuario(String nombre, String contrasena){
        boolean isUsuario = true;
        for (Usuario usuario : usuarios) {
            if (nombre.equals(usuario.getNombre()) && contrasena.equals(usuario.getContrasena())){
                isUsuario = true;
                break;
            } else {
                isUsuario = false;
            }
        }
        return isUsuario;
    }
    
    private void agregarElementos(){
        for (int i = 10; i <= 60; i+=2) {
            comboTamano.addItem(i+"");
            comboTamanoFuente.addItem(i+"");
        }
        for (int i = 0; i < fuentes.length; i++) {
            comboFuentes.addItem(fuentes[i]);
            modeloListaFuentes.addElement(fuentes[i]);
        }
    }
    
    private Usuario usuarioActual(String nombre, String contrasena){
        Usuario usuario = new Usuario();
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getNombre().equals(nombre) && usuarios.get(i).getContrasena().equals(contrasena)){
                usuario = usuarios.get(i);
                break;
            }
        }
        return usuario;
    }
    
    private void barraDeProgreso(JFrame frame) {
        dialProgressBar.pack();
        dialProgressBar.setVisible(true); 
        dialProgressBar.setLocationRelativeTo(this);
        Thread thread = new Thread() {
            public void run() {
                pBarCarga.setValue(0);
                while (pBarCarga.getValue() < 100) {
                    pBarCarga.setValue(pBarCarga.getValue() + 5);
                    try {
                        Thread.sleep(50);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    if (pBarCarga.getValue() == 100){
                        dialProgressBar.setVisible(false);
                        dialProgressBar.dispose();
                    }
                }
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        };
        thread.start();
    }
    
    private void barraDeProgreso(JDialog dial) {
        dialProgressBar.pack();
        dialProgressBar.setVisible(true); 
        dialProgressBar.setLocationRelativeTo(this);
        Thread thread = new Thread() {
            public void run() {
                pBarCarga.setValue(0);
                while (pBarCarga.getValue() < 100) {
                    pBarCarga.setValue(pBarCarga.getValue() + 5);
                    try {
                        Thread.sleep(50);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    if (pBarCarga.getValue() == 100){
                        dialProgressBar.setVisible(false);
                        dialProgressBar.dispose();
                    }
                }
                dial.pack();
                dial.setLocationRelativeTo(null);
                dial.setVisible(true);
            }
        };
        thread.start();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarEU;
    private javax.swing.JButton btnAtrasCU;
    private javax.swing.JButton btnAtrasEU;
    private javax.swing.JButton btnAtrasEditorTexto;
    private javax.swing.JButton btnColorEditorTexto;
    private javax.swing.JButton btnColorFuente;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnVolverFuente;
    private javax.swing.JComboBox<String> comboEstiloFuente;
    private javax.swing.JComboBox<String> comboEstilos;
    private javax.swing.JComboBox<String> comboFuentes;
    private javax.swing.JComboBox<String> comboTamano;
    private javax.swing.JComboBox<String> comboTamanoFuente;
    private javax.swing.JComboBox<String> comboTipoCU;
    private javax.swing.JDialog dialCrearUsuario;
    private javax.swing.JDialog dialEditarUsuario;
    private javax.swing.JDialog dialEditorTexto;
    private javax.swing.JDialog dialInfoSistema;
    private javax.swing.JDialog dialPersonalizarFuente;
    private javax.swing.JDialog dialProgressBar;
    private javax.swing.JFrame framePantallaInicioOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblColorEditorTexto;
    private javax.swing.JLabel lblColorFuente;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblContrasenaCU;
    private javax.swing.JLabel lblContrasenaEU;
    private javax.swing.JLabel lblEditarUsuario;
    private javax.swing.JLabel lblEditorTextoOS;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblEstiloFuente;
    private javax.swing.JLabel lblExploradorArchivoOS;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondoEditorTexto;
    private javax.swing.JLabel lblFondoFuente;
    private javax.swing.JLabel lblFondoInfoSistema;
    private javax.swing.JLabel lblFuente;
    private javax.swing.JLabel lblFuenteFuente;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIconoCrearUsuario;
    private javax.swing.JLabel lblIconoEditorTextoOS;
    private javax.swing.JLabel lblIconoExploradorArchivosOS;
    private javax.swing.JLabel lblIconoInfoSistemaOS;
    private javax.swing.JLabel lblInfoSistemaOS;
    private javax.swing.JLabel lblInicioSesion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreCU;
    private javax.swing.JLabel lblNombreEU;
    private javax.swing.JLabel lblOnOff;
    private javax.swing.JLabel lblTamano;
    private javax.swing.JLabel lblTamanoFuente;
    private javax.swing.JLabel lblTipoCU;
    private javax.swing.JLabel lblTituloCrearUsuario;
    private javax.swing.JLabel lblTituloInfoSistema;
    private javax.swing.JLabel lblTituloOS;
    private javax.swing.JLabel lblTituloPersonalizacionFuente;
    private javax.swing.JLabel lblUsuariosRegistrados;
    private javax.swing.JList<String> listFuente;
    private javax.swing.JList<String> listUsuariosRegistrados;
    private javax.swing.JMenuBar mBarEditorTexto;
    private javax.swing.JMenuBar mBarPrincipal;
    private javax.swing.JMenuItem mItemAbrirEditorTexto;
    private javax.swing.JMenuItem mItemColorLetraNavbar;
    private javax.swing.JMenuItem mItemCrearUsuario;
    private javax.swing.JMenuItem mItemEditarUsuario;
    private javax.swing.JMenuItem mItemEliminarUsuario;
    private javax.swing.JMenuItem mItemFondoColor;
    private javax.swing.JMenuItem mItemFondoImagen;
    private javax.swing.JMenuItem mItemFuente;
    private javax.swing.JMenuItem mItemGuardarEditorTexto;
    private javax.swing.JMenuItem mItemNavbarColor;
    private javax.swing.JMenu menuApagar;
    private javax.swing.JMenu menuArchivoEditorTexto;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuOpcionesUsuario;
    private javax.swing.JMenu menuPersonalizar;
    private javax.swing.JProgressBar pBarCarga;
    private javax.swing.JPanel panelEditorTexto;
    private javax.swing.JPanel panelInicioOS;
    private javax.swing.JPanel panelInicioSesion;
    private javax.swing.JTable tablaUsuarioInfoSistema;
    private javax.swing.JToggleButton tgBtnTitulo;
    private javax.swing.JTextArea txtAreaEditorTexto;
    private javax.swing.JTextField txtContrasenaCU;
    private javax.swing.JTextField txtContrasenaEU;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCU;
    private javax.swing.JTextField txtNombreEU;
    private javax.swing.JPasswordField txtPassContrasena;
    // End of variables declaration//GEN-END:variables
}
